"""renamed column in artist table.

Revision ID: 0f392cb43340
Revises: d9bc6677fd91
Create Date: 2022-08-11 23:53:48.665135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f392cb43340'
down_revision = 'd9bc6677fd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
