"""empty message

Revision ID: 284e4941febf
Revises: b9f8b190bacd
Create Date: 2022-08-16 02:31:38.538049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284e4941febf'
down_revision = 'b9f8b190bacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
