"""empty message

Revision ID: b2089de97804
Revises: 948dbd9e2cfa
Create Date: 2022-08-16 02:23:50.346159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2089de97804'
down_revision = '948dbd9e2cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_artist_id_fkey', 'show', 'artist', ['artist_id'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
